services:
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - farmashop
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - farmashop
  php:
    container_name: php-farmashop
    depends_on:
      - mysql
      - redis
    build:
      context: ./docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - farmashop
  composer:
    depends_on:
      - php
    image: composer:2.10.2
    container_name: composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: composer install
    networks:
      - farmashop
  nginx:
    depends_on:
      - php
    image: nginx:latest
    container_name: nginx
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - farmashop
  meilsearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped
    networks:
      - farmashop
  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    volumes:
      - floci-data:/app/data
    networks:
      - farmashop

networks:
  farmashop:

volumes:
  floci-data:

