name: Laravel's Test FarmaShop
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources project
        uses: actions/checkout@v7\

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: install dependencies
        run: composer install --prefer-dist

      - name: copy .env.example to .env
        run: cp .env.example .env

      - name: generate key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
